---
name: SkyBlock
description: A powerful core for SkyBlock servers edited UI by ZioCraft
author: GiantQuartz
editor: ZioCraft132
website: twitter.com/GiantQuartz
main: room17\SkyBlock\SkyBlock
version: 1.1.0
api: 3.0.0
...
